name: bento-gpu

# ノード1のIPアドレスを環境変数で指定
x-base-environment: &base-environment
  DATABASE_URL: postgresql://${POSTGRES_USER:-worker}:${POSTGRES_PASSWORD:-password}@${NODE1_IP:-192.168.1.100}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-taskdb}
  REDIS_URL: redis://${NODE1_IP:-192.168.1.100}:6379
  S3_URL: http://${NODE1_IP:-192.168.1.100}:9000
  S3_BUCKET: ${MINIO_BUCKET:-workflow}
  S3_ACCESS_KEY: ${MINIO_ROOT_USER:-admin}
  S3_SECRET_KEY: ${MINIO_ROOT_PASS:-password}
  RUST_LOG: ${RUST_LOG:-info}
  RUST_BACKTRACE: 1

services:
  # GPU証明エージェント（メイン）
  gpu_prove_agent0:
    image: ghcr.io/liray-unendlich/bnd-setup-prover:latest@sha256:e3d5e1c13522d6b3cd00c32d27a5426647129a8262f50c9b8a847b84b6ae0ef7
    restart: always
    runtime: nvidia
    mem_limit: 4G
    cpus: 4
    environment:
      <<: *base-environment
    entrypoint: /app/agent -t prove --redis-ttl ${REDIS_TTL:-57600}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

  # GPU証明エージェント（追加GPU用）
  gpu_prove_agent1:
    image: ghcr.io/liray-unendlich/bnd-setup-prover:latest@sha256:e3d5e1c13522d6b3cd00c32d27a5426647129a8262f50c9b8a847b84b6ae0ef7
    restart: always
    runtime: nvidia
    mem_limit: 4G
    cpus: 4
    environment:
      <<: *base-environment
    entrypoint: /app/agent -t prove --redis-ttl ${REDIS_TTL:-57600}
    profiles: [multi-gpu]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]

  # GPU証明エージェント（3番目のGPU用）
  gpu_prove_agent2:
    image: ghcr.io/liray-unendlich/bnd-setup-prover:latest@sha256:e3d5e1c13522d6b3cd00c32d27a5426647129a8262f50c9b8a847b84b6ae0ef7
    restart: always
    runtime: nvidia
    mem_limit: 4G
    cpus: 4
    environment:
      <<: *base-environment
    entrypoint: /app/agent -t prove --redis-ttl ${REDIS_TTL:-57600}
    profiles: [multi-gpu]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]

  # GPU証明エージェント（4番目のGPU用）
  gpu_prove_agent3:
    image: ghcr.io/liray-unendlich/bnd-setup-prover:latest@sha256:e3d5e1c13522d6b3cd00c32d27a5426647129a8262f50c9b8a847b84b6ae0ef7
    restart: always
    runtime: nvidia
    mem_limit: 4G
    cpus: 4
    environment:
      <<: *base-environment
    entrypoint: /app/agent -t prove --redis-ttl ${REDIS_TTL:-57600}
    profiles: [multi-gpu]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]
