name: release prover image

on:
  workflow_dispatch:
permissions:
  contents: read # リポジトリのコードをチェックアウトするための権限
  packages: write # GitHub Container Registryにイメージをプッシュするための権限
jobs:
  build-prover-image:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read # リポジトリのコードをチェックアウトするための権限
      packages: write # GitHub Container Registryにイメージをプッシュするための権限
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push prover Docker image
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        with:
          context: ./node2-gpu
          file: ./node2-gpu/dockerfile.prover
          push: true
          tags: ghcr.io/${{github.repository}}-prover:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
